# Permalinks
permalink:           /:short_year/:month/:title

# Setup
title:               "Ravi Udeshi"
tagline:             ""
url:                 http://new.raviudeshi.com
paginate:            10
baseurl:             ""
analytics_id:        "UA-180415-1"

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  twitter:           rkudeshi
  name:              Ravi Udeshi
  url:               http://raviudeshi.com
  email:             ""

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed


########################
#                      #
# ADDED CUSTOM BY RAVI #
#                      #
########################

# List of pages
pages_list:       
  about: '/about'
  archives: '/archives'
  contact: '/contact'
  subscribe: '/subscribe'

# Layout is "post" by default
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# Fix date/time generation
timezone: America/New_York

# jekyll-seo-tag stuff
logo: ""
# site-wide description (for Google snippet?)
description: ""
# for including in shared tweets?
twitter:
  username: rkudeshi

# Fix foootnotes on iOS
kramdown:
      footnote_backlink: "&#8617;&#xfe0e;"

feed:
  path: feed/index.xml

########################
#                      #
#  END CUSTOM BY RAVI  #
#                      #
########################