# Permalinks
permalink:           /:short_year/:month/:title

# Setup
title:               "@rkudeshi"
tagline:             "Jekyll-based blog"
url:                 http://rkudeshi.github.io
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ravi Udeshi
  url:               https://twitter.com/rkudeshi
  email:             example@example.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap

# ###########
# ADDED CUSTOM BY RAVI
# ##########
# List of pages
pages_list:       
  about: '/about'
  archives: '/archives'
  contact: '/contact'
  subscribe: '/subscribe'