---
title: "Oscars checklist 2023: All 54 films nominated and where to stream them"
---

As someone who participates in the "Oscars Death Race" - trying to watch every movie nominated at the Oscars in every category! - I like to put together a list of all the nominated films, sorted by their "highest" nominated category.

Here is the list of all 54 films nominated for this year's Oscars, with links for where to stream them. I hope you use this and watch some of these *great* films!

Personally, this has been a very stressful and busy year at work, so I've managed to watch fewer of the nominated films than usual. As of today, here's where I stand on the 54 total films:
- **20 feature films already seen.** Looks like I managed to see all of these in theaters!
- **19 feature films not seen yet.** These are mostly documentary and international films, some of which haven't been released in theaters or VOD yet. Unfortunately, it also includes 7 movies that were in theaters in my area, but I just missed them (or haven't had a chance to see them yet.)
- **15 short films.** Some theaters will play these a week or two before the ceremony, so I like to wait to watch them until then.

The big ceremony is on March 12, 2022 - looks like I've got some work to do if I want to watch everything before then!

### The big list

|------|-------------------------------------------------------------------|--------------------------|-------------------|------------------------------------------------------------------------------------------------------------------------------|
| Sort |                                Film                               |     Highest Category     | Total Nominations |                                                        Where to Watch                                                        |
|------|-------------------------------------------------------------------|--------------------------|-------------------|------------------------------------------------------------------------------------------------------------------------------|
|    1 | **Everything Everywhere All at Once**                             | Best Picture             |                11 | [Showtime](https://www.sho.com/titles/3493875/everything-everywhere-all-at-once)                                             |
|    2 | **All Quiet on the Western Front**                                | Best Picture             |                 9 | [Netflix](https://www.netflix.com/watch/81260280)                                                                            |
|    3 | **The Banshees of Inisherin**                                     | Best Picture             |                 9 | [HBO Max](https://play.hbomax.com/page/urn:hbo:page:GY3vttQpXywnCZwEAAAFm:type:feature)                                      |
|    4 | **Elvis**                                                         | Best Picture             |                 8 | [HBO Max](https://play.hbomax.com/page/urn:hbo:page:GYuwmqAnwQZa8kAEAAAE-:type:feature)                                      |
|    5 | **The Fabelmans**                                                 | Best Picture             |                 7 | [VOD](https://tv.apple.com/us/movie/the-fabelmans/umc.cmc.4lgvd75jcuqp79fuar3e9p9zh)                                         |
|    6 | **Tár**                                                           | Best Picture             |                 6 | [VOD](https://tv.apple.com/us/movie/umc.cmc.2408z7rnguoz01tcqidacvwc6)                                                       |
|    7 | **Top Gun: Maverick**                                             | Best Picture             |                 6 | [Paramount+](https://www.paramountplus.com/movies/video/Alcn0hcGx0HosdhcawKteH8DXh3RiOF7/)                                   |
|    8 | **Avatar: The Way of Water**                                      | Best Picture             |                 4 | TBD                                                                                                                          |
|    9 | **Triangle of Sadness**                                           | Best Picture             |                 3 | [VOD](https://www.amazon.com/gp/video/detail/amzn1.dv.gti.28b79702-d51e-448b-8c56-3c7fb448748d)                              |
|   10 | **Women Talking**                                                 | Best Picture             |                 2 | TBD                                                                                                                          |
|   11 | **Blonde**                                                        | Best Actress             |                 1 | [Netflix](https://www.netflix.com/watch/80174263)                                                                            |
|   12 | **To Leslie**                                                     | Best Actress             |                 1 | [VOD](https://tv.apple.com/us/movie/umc.cmc.34cf62tspe6al9pt2o9q8htgf)                                                       |
|   13 | **The Whale**                                                     | Best Actor               |                 3 | TBD                                                                                                                          |
|   14 | **Living**                                                        | Best Actor               |                 2 | TBD                                                                                                                          |
|   15 | **Aftersun**                                                      | Best Actor               |                 1 | [VOD](https://tv.apple.com/us/movie/umc.cmc.5y4yb2dmuaubbfamqzja4pjry)                                                       |
|   16 | **Black Panther: Wakanda Forever**                                | Best Supporting Actress  |                 5 | Disney+ (soon)                                                                                                               |
|   17 | **Causeway**                                                      | Best Supporting Actor    |                 1 | [Apple TV+](https://tv.apple.com/us/movie/causeway/umc.cmc.30p2zn6vd14159dorn1vo68el)                                        |
|   18 | **Glass Onion: A Knives Out Mystery**                             | Best Adapted Screenplay  |                 1 | [Netflix](https://www.netflix.com/watch/81458416)                                                                            |
|   19 | **Argentina, 1985**                                               | Best International Film  |                 1 | [Amazon Prime](https://www.amazon.com/gp/video/detail/amzn1.dv.gti.2980e4f8-464c-4b85-93dc-f93c9941dc2b)                     |
|   20 | **Close**                                                         | Best International Film  |                 1 | TBD                                                                                                                          |
|   21 | **EO**                                                            | Best International Film  |                 1 | TBD                                                                                                                          |
|   22 | **The Quiet Girl**                                                | Best International Film  |                 1 | TBD                                                                                                                          |
|   23 | **Guillermo Del Toro's Pinnochio**                                | Best Animated Feature    |                 1 | [Netflix](https://www.netflix.com/watch/80218455)                                                                            |
|   24 | **Marcel the Shell with Shoes On**                                | Best Animated Feature    |                 1 | [VOD](https://tv.apple.com/us/movie/umc.cmc.23mlvs843dhgo7ir7bk727xm2)                                                       |
|   25 | **Puss in Boots: The Last Wish**                                  | Best Animated Feature    |                 1 | [VOD](https://tv.apple.com/us/movie/umc.cmc.3ysvrfdjp7h6q8dt73t3bq23i)                                                       |
|   26 | **The Sea Beast**                                                 | Best Animated Feature    |                 1 | [Netflix](https://www.netflix.com/watch/81018682)                                                                            |
|   27 | **Turning Red**                                                   | Best Animated Feature    |                 1 | [Disney+](https://www.disneyplus.com/movies/turning-red/4mFPCXJi7N2m)                                                        |
|   28 | **A House Made of Splinters**                                     | Best Documentary Feature |                 1 | TBD                                                                                                                          |
|   29 | **All That Breathes**                                             | Best Documentary Feature |                 1 | TBD                                                                                                                          |
|   30 | **All the Beauty and the Bloodshed**                              | Best Documentary Feature |                 1 | TBD                                                                                                                          |
|   31 | **Fire of Love**                                                  | Best Documentary Feature |                 1 | [Disney+](https://www.disneyplus.com/movies/fire-of-love/1hC7erRfsl3B)                                                       |
|   32 | **Navalny**                                                       | Best Documentary Feature |                 1 | [HBO Max](https://play.hbomax.com/page/urn:hbo:page:GYmFp9ATv1JSBmwEAAACW:type:feature)                                      |
|   33 | **Bardo, False Chronicle of a Handful of Truths**                 | Best Cinematography      |                 1 | [Netflix](https://www.netflix.com/watch/81249430)                                                                            |
|   34 | **Empire of Light**                                               | Best Cinematography      |                 1 | TBD                                                                                                                          |
|   35 | **The Batman**                                                    | Best Visual Effects      |                 3 | [HBO Max](https://play.hbomax.com/page/urn:hbo:page:GYiDbSAmIpMNvYAEAAAAI:type:feature)                                      |
|   36 | **Babylon**                                                       | Best Production Design   |                 3 | TBD                                                                                                                          |
|   37 | **Mrs. Harris Goes to Paris**                                     | Best Costume Design      |                 1 | [Peacock](https://www.peacocktv.com/watch/asset/movies/mrs.-harris-goes-to-paris/e2ee9073-eb4b-3650-8d87-d7290196949f)       |
|   38 | **RRR**                                                           | Best Song                |                 1 | [Netflix](https://www.netflix.com/watch/81476453)                                                                            |
|   39 | **Tell It Like A Woman**                                          | Best Song                |                 1 | TBD                                                                                                                          |
|   40 | **An Irish Goodbye**                                              | Best Live Action Short   |                 1 | TBD                                                                                                                          |
|   41 | **Ivalu**                                                         | Best Live Action Short   |                 1 | TBD                                                                                                                          |
|   42 | **Le Pupille**                                                    | Best Live Action Short   |                 1 | [Disney+](https://www.disneyplus.com/movies/le-pupille/2Bunod4lQMSe)                                                                                                                          |
|   43 | **Night Ride**                                                    | Best Live Action Short   |                 1 | [New Yorker](https://www.newyorker.com/video/watch/the-new-yorker-documentary-night-ride?c=series) |
|   44 | **The Red Suitcase**                                              | Best Live Action Short   |                 1 | TBD                                                                                                                          |
|   45 | **An Ostrich Told Me The World Is Fake And I Think I Believe It** | Best Animated Short      |                 1 | TBD                                                                                                                          |
|   46 | **Ice Merchants**                                                 | Best Animated Short      |                 1 | [New Yorker](https://www.newyorker.com/video/watch/the-new-yorker-shorts-ice-merchants-a-father-and-son-brave-perilous-heights?c=series)                                                                                                                          |
|   47 | **My Year of Dicks**                                              | Best Animated Short      |                 1 | [Vimeo](https://vimeo.com/785947192?embedded=true&source=vimeo_logo&owner=1833463)                                                                                                                          |
|   48 | **The Boy, The Mole, The Fox and the Horse**                      | Best Animated Short      |                 1 | [Apple TV+](https://tv.apple.com/us/movie/the-boy-the-mole-the-fox-and-the-horse/umc.cmc.2aenzye90tqkj7iy0131oom9x)                                                                                                                          |
|   49 | **The Flying Sailor**                                             | Best Animated Short      |                 1 | [New Yorker](https://www.newyorker.com/video/watch/the-new-yorker-documentary-flying-sailor)                                                                                                                          |
|   50 | **Haulout**                                                       | Best Documentary Short   |                 1 | [New Yorker](https://www.newyorker.com/video/watch/the-new-yorker-documentary-haulout?q=haulout)                                                                                                                          |
|   51 | **How Do You Measure a Year**                                     | Best Documentary Short   |                 1 | TBD                                                                                                                          |
|   52 | **Stranger at the Gate**                                          | Best Documentary Short   |                 1 | [New Yorker](https://www.newyorker.com/video/watch/stranger-at-the-gate)                                                                                                                          |
|   53 | **The Elephant Whisperers**                                       | Best Documentary Short   |                 1 | [Netflix](https://www.netflix.com/title/81312835)                                                                                                                          |
|   54 | **The Martha Mitchell Effect**                                    | Best Documentary Short   |                 1 | [Netflix](https://www.netflix.com/title/81488054)                                                                                                                          |
|------|-------------------------------------------------------------------|--------------------------|-------------------|------------------------------------------------------------------------------------------------------------------------------|
